import { useState } from 'react';
import { Icon } from './ui';
import { ChevronDown } from 'lucide-react';

// Data source for the FAQs
const faqData = [
    {
        id: 1,
        question: 'What is Swirl?',
        answer:
            'Swirl is a privacy-preserving MNT pool deployed on Mantle Sepolia Network. It allows users to deposit a fixed amount of MNT and later withdraw it to a different address without linking the deposit and withdrawal, using zero-knowledge proofs.'
    },
    {
        id: 2,
        question: 'How does Swirl preserve privacy?',
        answer:
            'Swirl uses zero-knowledge proofs to prove ownership of a deposit without revealing which one, a Poseidon-hashed Merkle tree to store deposits, and nullifiers to prevent double spending without revealing identities.'
    },
    {
        id: 3,
        question: 'What is the deposit amount?',
        answer:
            'Each deposit has a fixed denomination of 1 MNT, plus a 0.1 MNT protocol fee. The total required to deposit is 1.1 MNT.'
    },
    {
        id: 4,
        question: 'Why is the denomination fixed?',
        answer:
            'Fixed denominations are required for privacy. If users deposited different amounts, it would be easy to link deposits to withdrawals. Using a fixed amount ensures all withdrawals look identical on-chain.'
    },
    {
        id: 5,
        question: 'Can I deposit more than once?',
        answer:
            'Yes. Each deposit creates a new commitment in the Merkle tree, and each commitment can be withdrawn once.'
    },
    {
        id: 6,
        question: 'What is a commitment?',
        answer:
            'A commitment is a Poseidon hash of a secret and a nullifier. This commitment is stored in the Merkle tree when you deposit.'
    },
    {
        id: 7,
        question: 'What is a nullifier and why is it important?',
        answer:
            'A nullifier is revealed during withdrawal and prevents the same deposit from being withdrawn twice. Once used, it is permanently marked as spent.'
    },
    {
        id: 8,
        question: 'Can someone steal my funds if they see my deposit?',
        answer:
            'No. Funds can only be withdrawn by someone who knows the original secret and nullifier and can generate a valid zero-knowledge proof.'
    },
    {
        id: 9,
        question: 'How does withdrawal work?',
        answer:
            'To withdraw, you submit a zero-knowledge proof, a valid Merkle root, your nullifier hash, and a recipient address. If valid, 1 MNT is sent to the recipient.'
    },
    {
        id: 10,
        question: 'Can I withdraw to a different wallet?',
        answer:
            'Yes. The withdrawal address does not need to match the deposit address, which is the core privacy feature of Swirl.'
    },
    {
        id: 11,
        question: 'Is there a time delay between deposit and withdrawal?',
        answer:
            'There is no enforced delay at the smart contract level, but withdrawing immediately may reduce your anonymity set.'
    },
    {
        id: 12,
        question: 'What is the Merkle tree size?',
        answer:
            'The Merkle tree has a depth of 20, supporting up to 1,048,576 deposits. Once full, no more deposits can be made.'
    },
    {
        id: 13,
        question: 'What are known roots?',
        answer:
            'Known roots are valid Merkle roots generated by deposits. Withdrawals are only accepted if the root is known.'
    },
    {
        id: 14,
        question: 'What happens if I lose my secret or nullifier?',
        answer:
            'Your funds will be lost permanently. Swirl is non-custodial and cannot recover secrets. Always back up your deposit data securely.'
    },
    {
        id: 15,
        question: 'Is Swirl non-custodial?',
        answer:
            'Yes. Only the smart contract holds funds, and withdrawals are governed entirely by cryptographic proofs.'
    },
    {
        id: 16,
        question: 'Are there protocol fees?',
        answer:
            'Yes. A 0.1 MNT fee is charged per deposit and collected by the protocol owner.'
    },
    {
        id: 17,
        question: 'Can the protocol be paused?',
        answer:
            'Yes. The owner can pause the contract in emergencies, disabling deposits and withdrawals.'
    },
    {
        id: 18,
        question: 'Is there any form of sanctions or blacklisting?',
        answer:
            'Optionally, the owner can blacklist addresses. Blacklisted addresses cannot deposit or receive withdrawals.'
    },
    {
        id: 19,
        question: 'Can the owner steal user funds?',
        answer:
            'No. The owner cannot withdraw user deposits and can only withdraw protocol fees.'
    },
    {
        id: 20,
        question: 'What cryptography does Swirl use?',
        answer:
            'Swirl uses the Poseidon hash function, Merkle trees, and Noir-compatible zero-knowledge proofs, optimized for ZK efficiency.'
    },
    {
        id: 21,
        question: 'Is this production-ready?',
        answer:
            'This deployment is testing-oriented with a 1 MNT denomination and should be treated as experimental.'
    },
    {
        id: 22,
        question: 'Where can I use Swirl?',
        answer:
            'You can access Swirl at https://swirl-two.vercel.app/.'
    },
    {
        id: 23,
        question: 'What network is Swirl deployed on?',
        answer:
            'Swirl is deployed on Mantle Sepolia Network and uses MNT as its native asset.'
    },
    {
        id: 24,
        question: 'Is my privacy guaranteed?',
        answer:
            'Swirl provides on-chain privacy, not total anonymity. Privacy depends on the anonymity set, operational security, and withdrawal behavior.'
    }
];



type FAQItemProps = {
    id: number
    question: string
    answer: string
    isOpen: boolean
    onToggle: (id: number) => void
}

const FAQItem = ({ id, question, answer, isOpen, onToggle }: FAQItemProps) => {
    return (
        <div className="border border-white/10 rounded-xl bg-black/40">
            <button
                type="button"
                onClick={() => onToggle(id)}
                className="w-full flex items-center justify-between gap-4 px-4 py-3 text-left"
            >
                <span className="text-[12px] sm:text-[13px] font-medium text-white">
                    {question}
                </span>

                <ChevronDown
                    name="chevron-down"
                    size={14}
                    color="#fff"
                    className={`transition-transform ${isOpen ? 'rotate-180 transition-all duration-500' : ''}`}
                />
            </button>

            {isOpen && (
                <div className="px-4 pb-4 text-[11px] sm:text-[12px] text-[#888888] leading-relaxed">
                    {answer}
                </div>
            )}
        </div>
    )
}


export const FAQList = () => {
    const [openIds, setOpenIds] = useState<number[]>([])

    const handleToggle = (id: number) => {
        setOpenIds((prev) =>
            prev.includes(id)
                ? prev.filter((openId) => openId !== id)
                : [...prev, id]
        )
    }

    return (
        <section className="mx-auto px-4 flex flex-col gap-8">
            {/* Header */}
            <div className="flex flex-col gap-3 items-center">
                <div className="flex items-center gap-2">
                    <Icon name="shield" size={16} color="#00FFB3" />
                    <span className="text-[11px] font-semibold uppercase tracking-wider text-[#00FFB3]">
                        FAQ
                    </span>
                </div>

                <h1 className="text-[22px] sm:text-[26px] font-semibold text-white">
                    Frequently Asked Questions
                </h1>

                <p className="text-[12px] sm:text-[13px] text-[#888888] max-w-[520px] text-center">
                    Learn how Swirl preserves privacy, how deposits and withdrawals work,
                    and what guarantees the protocol provides.
                </p>
            </div>

            {/* FAQ List */}
            <div className="grid grid-cols-2 gap-4 auto-rows-min items-start">
                {faqData.map((item) => (
                    <FAQItem
                        key={item.id}
                        id={item.id}
                        question={item.question}
                        answer={item.answer}
                        isOpen={openIds.includes(item.id)}
                        onToggle={handleToggle}
                    />
                ))}
            </div>
        </section>
    )
}

